// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbmptfblvaedgtdlmwlx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNibXB0ZmJsdmFlZGd0ZGxtd2x4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDQ3MTQsImV4cCI6MjA2NTQ4MDcxNH0.-WWQi0nAVHFb9EzO-xveGS2cTxMqvsUsyIsKx3yde-Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});